### ISSUE TITLE
Push access for @Rossiar

### ISSUE THREAD

**Issue by janstuemmel** [janstuemmel/csgo-log#5]
@Rossiar. You have no email in your account so i contact you with this issue...

Wanna have push access for this repository? You commited a few important changes to this library and you have a real use case for this lib at @faceit.

**Comment by Rossiar** [comment]
I'd love to, I imagine that our usage of this library (thanks for writing it btw) will only increase as time goes on and we will care about more and more events from the server logs.

**Comment by janstuemmel** [comment]
you have push access. hf :)
