### ISSUE TITLE
V2 Versioning

### ISSUE THREAD

**Issue by Rossiar** [janstuemmel/csgo-log#6]
Golang is stopping me from importing at v2.0.1 (I realise this is the same reason I kept my fork in v2.0.0) because of the language rules that state "If an old package and a new package have the same import path, the new package must be backwards compatible with the old package." (https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)
```
go get github.com/janstuemmel/csgo-log@v2.0.1
go: finding github.com/janstuemmel/csgo-log v2.0.1
go: finding github.com/janstuemmel/csgo-log v2.0.1
go get github.com/janstuemmel/csgo-log@v2.0.1: github.com/janstuemmel/csgo-log@v2.0.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I think the fix is to change v2.0.0 and v2.0.1 to be v1.1.0 and v1.1.1 respectively, since I don't believe I introduced any breaking changes when I committed the first time and this will make `go get` happy. I figure this won't break for anyone else since you can't get the module as a dependency at these new versions anyway due to the error above.

**Comment by janstuemmel** [comment]
wanna do that, or should i fix it? you have push access now btw

**Comment by Rossiar** [comment]
I think you need to do it, push access doesn't allow me to mess about with the releases on github.

**Comment by Rossiar** [comment]
I've done it, thanks for granting me access :smile:

**Comment by janstuemmel** [comment]
Golang blog post about v2 versioning:

https://blog.golang.org/v2-go-modules
